apiVersion: mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: example-mariadb
spec:
  masters: 1
  replicas: 0
  mariadb_password: TODO
  mariadb_image: mariadb:10.4
  mariadb_pvc_storage_request: 1Gi
